namespace Order_Food_Online.Areas.Resturant.Models
{
    public enum City
    {
        Alexandria, 
        Aswan, 
        Asyut, 
        Beheira, 
        BeniSuef, 
        Cairo, 
        Dakahlia, 
        Damietta, 
        Faiyum, 
        Gharbia, 
        Giza, 
        Ismailia, 
        KafrElSheikh, 
        Luxor, 
        Matrouh, 
        Minya, 
        Monufia, 
        NewValley, 
        NorthSinai, 
        PortSaid, 
        Qalyubia, 
        Qena, 
        RedSea, 
        Sharqia, 
        Sohag, 
        SouthSinai
    }
}
